added new way to compile for now to avoid the error or make (fsm.cpp:(.text+0x126): undefined reference to `stateVirtual::stateVirtual(int)\'), may need to make sure the files are linked properly